Dropdown assets
safetibase/safetibase pull request #43
Opened 2024-05-22 10:47 UTC by ayoblvck

fixes  "When a new hazard is added, the hazard is tagged against all stages . I.e demolition, construction, commission etc. Add in functionality which allows you to select i.e. construction, commission etc  from a pick list field

Instead of all categories selected by default, let user select the stage they want rather than unselecting them"

2024-06-13 09:01 UTC, ayoblvck commented on SiteAssets/pages/3.0/scripts/CDM.DATA.CONTROLLER.js
> +        if (callback && callback === Function) {
This throws an error when call back is not a function hence the second condition

2024-06-13 13:48 UTC, JHolland98 requested changes

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/html/new.hazard.form.html
> +            lbl = '<div class=""tpos-lbl"">Selected asset(s)</div>';
Remove one set of the double quotes here

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/html/new.hazard.form.html
> +            }}
Can we tab back lines 360 to 370 so they're aligned properly

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/html/new.hazard.form.html
> +                }
tab back lines 601 and 602 until they're lined correctly

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/scripts/CDM.DATA.CONTROLLER.js
> +                toastr.success(check[1] + " hazard(s) successfully added")
Remove the stuff about the check - it's better to have a toast for each successful hazard creation

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/scripts/CDM.DATA.CONTROLLER.js
> +    set: function(lst, data, callback, check) {
remove the check parameter

2024-06-13 13:48 UTC, JHolland98 commented on SiteAssets/pages/3.0/scripts/CDM.DATA.CONTROLLER.js
> +                toastr.error("hazard(s) not added")
Remove the stuff about the check

2024-06-14 15:25 UTC, JHolland98 approved these changes

2024-06-14 15:25 UTC, merged